version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    volumes:
      - ../:/var/www/html
      - ../uploads:/var/www/html/uploads
    environment:
      - DB_HOST=db
      - DB_NAME=it_inventory
      - DB_USER=admin
      - DB_PASS=@#8520@#

  db:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: it_inventory
      MYSQL_USER: admin
      MYSQL_PASSWORD: "@#8520@#"
      MYSQL_ROOT_PASSWORD: "@#8520@#"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: