SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT 
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'ready_machines' 
  AND (COLUMN_NAME LIKE 'warranty%' OR COLUMN_NAME = 'has_warranty') 
ORDER BY ORDINAL_POSITION;
